import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1785603280632 implements MigrationInterface {
    name = 'Migration1785603280632'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_user_role"`);
        await queryRunner.query(`ALTER TABLE "pos_terminal" DROP CONSTRAINT "FK_pos_terminal_tenant"`);
        await queryRunner.query(`ALTER TABLE "tax_config" DROP CONSTRAINT "FK_tax_config_tenant"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_category_tenant"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_product_category"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_product_tenant"`);
        await queryRunner.query(`ALTER TABLE "variation_group" DROP CONSTRAINT "FK_variation_group_product"`);
        await queryRunner.query(`ALTER TABLE "variation_option" DROP CONSTRAINT "FK_variation_option_group"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_customer_tenant"`);
        await queryRunner.query(`ALTER TABLE "order_item_variation" DROP CONSTRAINT "FK_order_item_variation_item"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_order_item_order"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_order_tenant"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_order_terminal"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_order_customer"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_order_cashier"`);
        await queryRunner.query(`ALTER TABLE "feature_flag" DROP CONSTRAINT "FK_feature_flag_tenant"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" DROP CONSTRAINT "FK_terminal_event_terminal"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" DROP CONSTRAINT "FK_terminal_event_event"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" DROP CONSTRAINT "FK_terminal_event_user"`);
        await queryRunner.query(`ALTER TABLE "discount" DROP CONSTRAINT "FK_discount_tenant"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_user_email_tenant"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "UQ_category_name_tenant"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "UQ_product_sku_tenant"`);
        await queryRunner.query(`ALTER TABLE "feature_flag" DROP CONSTRAINT "UQ_feature_flag_key_tenant"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" DROP CONSTRAINT "UQ_terminal_event"`);
        await queryRunner.query(`ALTER TABLE "order" ADD "reason" character varying`);
        await queryRunner.query(`ALTER TABLE "order" ADD "refundAmount" numeric(10,2)`);
        await queryRunner.query(`ALTER TYPE "public"."order_status_enum" RENAME TO "order_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum" AS ENUM('open', 'in_progress', 'completed', 'cancelled', 'voided', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" TYPE "public"."order_status_enum" USING "status"::"text"::"public"."order_status_enum"`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" SET DEFAULT 'completed'`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."order_type_enum" RENAME TO "order_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."order_ordertype_enum" AS ENUM('dine_in', 'take_away')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "orderType" TYPE "public"."order_ordertype_enum" USING "orderType"::"text"::"public"."order_ordertype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."order_discount_type_enum" RENAME TO "order_discount_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."order_discounttype_enum" AS ENUM('percentage', 'amount', 'none')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "discountType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "discountType" TYPE "public"."order_discounttype_enum" USING "discountType"::"text"::"public"."order_discounttype_enum"`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "discountType" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."order_discount_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."order_payment_method_enum" RENAME TO "order_payment_method_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."order_paymentmethod_enum" AS ENUM('cash', 'card')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "paymentMethod" TYPE "public"."order_paymentmethod_enum" USING "paymentMethod"::"text"::"public"."order_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_payment_method_enum_old"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ALTER COLUMN "assignedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_30d87f4cea5b6fe30125c87e770" UNIQUE ("emailAddress", "tenantId")`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "UQ_33e48bdf6a67804c0e370494285" UNIQUE ("name", "tenantId")`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "UQ_505d4bf5fa042f7254adff9d6ad" UNIQUE ("sku", "tenantId")`);
        await queryRunner.query(`ALTER TABLE "feature_flag" ADD CONSTRAINT "UQ_49b0237d95e9f0164218ecafd52" UNIQUE ("key", "tenantId")`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ADD CONSTRAINT "UQ_6da2e59aef17686cd2542bd812e" UNIQUE ("terminalId", "eventId")`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_terminal" ADD CONSTRAINT "FK_48670d8e736f8963d21f6e0e6af" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_config" ADD CONSTRAINT "FK_393c8393b8ac62a5a7515957e0a" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_ecfa4b687173f2c9fe47b918c3c" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_ff0c0301a95e517153df97f6812" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_08293ca31a601d3cd0228120bc9" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variation_group" ADD CONSTRAINT "FK_b491779bd0d687e0d725c993d1c" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variation_option" ADD CONSTRAINT "FK_e0fbec2c8c84d3fa34c00669882" FOREIGN KEY ("groupId") REFERENCES "variation_group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_3a9e57ca250bf376b9558474912" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_variation" ADD CONSTRAINT "FK_202c46d82d3df741e8084999721" FOREIGN KEY ("orderItemId") REFERENCES "order_item"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_7853202400ba8726242baa7a916" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_d3da36152ac8504089d916f742b" FOREIGN KEY ("terminalId") REFERENCES "pos_terminal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_124456e637cca7a415897dce659" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_30fd5a3eac6bdbf80f74981fbc0" FOREIGN KEY ("cashierId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flag" ADD CONSTRAINT "FK_6d71049e9b27b7c73c266168c64" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ADD CONSTRAINT "FK_bc385165855af6aa3aedd55ef12" FOREIGN KEY ("terminalId") REFERENCES "pos_terminal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ADD CONSTRAINT "FK_1c71a0838afa97cd9953eac2575" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ADD CONSTRAINT "FK_f97067e2a53a4e1ab01ce282ea5" FOREIGN KEY ("assignedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount" ADD CONSTRAINT "FK_6e7d1396be015cb18f79d98e971" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "discount" DROP CONSTRAINT "FK_6e7d1396be015cb18f79d98e971"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" DROP CONSTRAINT "FK_f97067e2a53a4e1ab01ce282ea5"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" DROP CONSTRAINT "FK_1c71a0838afa97cd9953eac2575"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" DROP CONSTRAINT "FK_bc385165855af6aa3aedd55ef12"`);
        await queryRunner.query(`ALTER TABLE "feature_flag" DROP CONSTRAINT "FK_6d71049e9b27b7c73c266168c64"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_30fd5a3eac6bdbf80f74981fbc0"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_124456e637cca7a415897dce659"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_d3da36152ac8504089d916f742b"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_7853202400ba8726242baa7a916"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0"`);
        await queryRunner.query(`ALTER TABLE "order_item_variation" DROP CONSTRAINT "FK_202c46d82d3df741e8084999721"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_3a9e57ca250bf376b9558474912"`);
        await queryRunner.query(`ALTER TABLE "variation_option" DROP CONSTRAINT "FK_e0fbec2c8c84d3fa34c00669882"`);
        await queryRunner.query(`ALTER TABLE "variation_group" DROP CONSTRAINT "FK_b491779bd0d687e0d725c993d1c"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_08293ca31a601d3cd0228120bc9"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_ff0c0301a95e517153df97f6812"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_ecfa4b687173f2c9fe47b918c3c"`);
        await queryRunner.query(`ALTER TABLE "tax_config" DROP CONSTRAINT "FK_393c8393b8ac62a5a7515957e0a"`);
        await queryRunner.query(`ALTER TABLE "pos_terminal" DROP CONSTRAINT "FK_48670d8e736f8963d21f6e0e6af"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" DROP CONSTRAINT "UQ_6da2e59aef17686cd2542bd812e"`);
        await queryRunner.query(`ALTER TABLE "feature_flag" DROP CONSTRAINT "UQ_49b0237d95e9f0164218ecafd52"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "UQ_505d4bf5fa042f7254adff9d6ad"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "UQ_33e48bdf6a67804c0e370494285"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_30d87f4cea5b6fe30125c87e770"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ALTER COLUMN "assignedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."order_payment_method_enum_old" AS ENUM('cash', 'card')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "paymentMethod" TYPE "public"."order_payment_method_enum_old" USING "paymentMethod"::"text"::"public"."order_payment_method_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."order_paymentmethod_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."order_payment_method_enum_old" RENAME TO "order_payment_method_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."order_discount_type_enum_old" AS ENUM('percentage', 'amount', 'none')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "discountType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "discountType" TYPE "public"."order_discount_type_enum_old" USING "discountType"::"text"::"public"."order_discount_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "discountType" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."order_discounttype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."order_discount_type_enum_old" RENAME TO "order_discount_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."order_type_enum_old" AS ENUM('dine_in', 'take_away')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "orderType" TYPE "public"."order_type_enum_old" USING "orderType"::"text"::"public"."order_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."order_ordertype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."order_type_enum_old" RENAME TO "order_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum_old" AS ENUM('open', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" TYPE "public"."order_status_enum_old" USING "status"::"text"::"public"."order_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" SET DEFAULT 'completed'`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."order_status_enum_old" RENAME TO "order_status_enum"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "refundAmount"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ADD CONSTRAINT "UQ_terminal_event" UNIQUE ("terminalId", "eventId")`);
        await queryRunner.query(`ALTER TABLE "feature_flag" ADD CONSTRAINT "UQ_feature_flag_key_tenant" UNIQUE ("key", "tenantId")`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "UQ_product_sku_tenant" UNIQUE ("sku", "tenantId")`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "UQ_category_name_tenant" UNIQUE ("name", "tenantId")`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_user_email_tenant" UNIQUE ("emailAddress", "tenantId")`);
        await queryRunner.query(`ALTER TABLE "discount" ADD CONSTRAINT "FK_discount_tenant" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ADD CONSTRAINT "FK_terminal_event_user" FOREIGN KEY ("assignedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ADD CONSTRAINT "FK_terminal_event_event" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminal_event" ADD CONSTRAINT "FK_terminal_event_terminal" FOREIGN KEY ("terminalId") REFERENCES "pos_terminal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flag" ADD CONSTRAINT "FK_feature_flag_tenant" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_order_cashier" FOREIGN KEY ("cashierId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_order_customer" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_order_terminal" FOREIGN KEY ("terminalId") REFERENCES "pos_terminal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_order_tenant" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_order_item_order" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_variation" ADD CONSTRAINT "FK_order_item_variation_item" FOREIGN KEY ("orderItemId") REFERENCES "order_item"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_customer_tenant" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variation_option" ADD CONSTRAINT "FK_variation_option_group" FOREIGN KEY ("groupId") REFERENCES "variation_group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variation_group" ADD CONSTRAINT "FK_variation_group_product" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_product_tenant" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_product_category" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_category_tenant" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_config" ADD CONSTRAINT "FK_tax_config_tenant" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_terminal" ADD CONSTRAINT "FK_pos_terminal_tenant" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_user_role" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
