env_vars:
  NODE_ENV: production
  REGISTRY: PLACEHOLDER_REGISTRY_URL
  APP_IMAGE: PLACEHOLDER_IMAGE_NAME:latest-uat
  MIGRATION_IMAGE: PLACEHOLDER_IMAGE_NAME-migration:latest-uat
  SERVICE_NAME: app-backend
  DOMAIN: PLACEHOLDER_DOMAIN
  POSTGRES_DB: app
  POSTGRES_USER: PLACEHOLDER_DB_USER
  POSTGRES_PASSWORD: PLACEHOLDER_DB_PASSWORD
  DATABASE_VOLUME: app-database-storage
  REDIS_VOLUME: app-redis-storage
  MINIO_ACCESS_KEY: PLACEHOLDER_MINIO_ACCESS_KEY
  MINIO_SECRET_KEY: PLACEHOLDER_MINIO_SECRET_KEY
  MINIO_BUCKET: media
  MASTER_SECRET: PLACEHOLDER_SECRET
