export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_TENANT = 'INVALID_TENANT',
  MISSING_TENANT_ID = 'MISSING_TENANT_ID',
  USER_SERIALIZATION_FAILED = 'USER_SERIALIZATION_FAILED',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
  USER_DELETE_FAILED = 'USER_DELETE_FAILED',
  INVALID_ROLE = 'INVALID_ROLE',

  // Role
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_NAME_CONFLICT = 'ROLE_NAME_CONFLICT',
  ROLE_UPDATE_FAILED = 'ROLE_UPDATE_FAILED',
  ROLE_DELETE_FAILED = 'ROLE_DELETE_FAILED',

  // Tenant
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_UPDATE_FAILED = 'TENANT_UPDATE_FAILED',
  TENANT_DELETE_FAILED = 'TENANT_DELETE_FAILED',

  // Terminal
  TERMINAL_NOT_FOUND = 'TERMINAL_NOT_FOUND',
  TERMINAL_UPDATE_FAILED = 'TERMINAL_UPDATE_FAILED',

  // Category
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_CONFLICT = 'CATEGORY_NAME_CONFLICT',
  CATEGORY_UPDATE_FAILED = 'CATEGORY_UPDATE_FAILED',

  // Product
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_CONFLICT = 'PRODUCT_SKU_CONFLICT',

  // Customer
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',

  // Order
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  CASHIER_NOT_FOUND = 'CASHIER_NOT_FOUND',
  ORDER_CANNOT_BE_VOIDED = 'ORDER_CANNOT_BE_VOIDED',
  ORDER_CANNOT_BE_REFUNDED = 'ORDER_CANNOT_BE_REFUNDED',
  REFUND_AMOUNT_EXCEEDS_TOTAL = 'REFUND_AMOUNT_EXCEEDS_TOTAL',

  // Event
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  TERMINAL_ALREADY_ASSIGNED_TO_EVENT = 'TERMINAL_ALREADY_ASSIGNED_TO_EVENT',
  TERMINAL_EVENT_NOT_FOUND = 'TERMINAL_EVENT_NOT_FOUND',

  // Table
  TABLE_NOT_FOUND = 'TABLE_NOT_FOUND',

  // Membership
  MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_ALREADY_EXISTS = 'MEMBERSHIP_ALREADY_EXISTS',

  // TaxConfig
  TAX_CONFIG_NOT_FOUND = 'TAX_CONFIG_NOT_FOUND',
  TAX_CONFIG_UPDATE_FAILED = 'TAX_CONFIG_UPDATE_FAILED',

  // FeatureFlag
  FEATURE_FLAG_NOT_FOUND = 'FEATURE_FLAG_NOT_FOUND',
  FEATURE_FLAG_KEY_CONFLICT = 'FEATURE_FLAG_KEY_CONFLICT',
  FEATURE_FLAG_UPDATE_FAILED = 'FEATURE_FLAG_UPDATE_FAILED',

  // Discount
  DISCOUNT_NOT_FOUND = 'DISCOUNT_NOT_FOUND',
  DISCOUNT_CODE_CONFLICT = 'DISCOUNT_CODE_CONFLICT',
  DISCOUNT_UPDATE_FAILED = 'DISCOUNT_UPDATE_FAILED',
  DISCOUNT_EXPIRED = 'DISCOUNT_EXPIRED',
  DISCOUNT_INACTIVE = 'DISCOUNT_INACTIVE',

  // Generic
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
