export enum ErrorCode {
  // Auth
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_TENANT = 'INVALID_TENANT',
  MISSING_TENANT_ID = 'MISSING_TENANT_ID',
  USER_SERIALIZATION_FAILED = 'USER_SERIALIZATION_FAILED',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
  USER_DELETE_FAILED = 'USER_DELETE_FAILED',
  INVALID_ROLE = 'INVALID_ROLE',

  // Role
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_UPDATE_FAILED = 'ROLE_UPDATE_FAILED',
  ROLE_DELETE_FAILED = 'ROLE_DELETE_FAILED',

  // Tenant
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_UPDATE_FAILED = 'TENANT_UPDATE_FAILED',
  TENANT_DELETE_FAILED = 'TENANT_DELETE_FAILED',

  // Terminal
  TERMINAL_NOT_FOUND = 'TERMINAL_NOT_FOUND',
  TERMINAL_UPDATE_FAILED = 'TERMINAL_UPDATE_FAILED',

  // Category
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_CONFLICT = 'CATEGORY_NAME_CONFLICT',
  CATEGORY_UPDATE_FAILED = 'CATEGORY_UPDATE_FAILED',

  // Product
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_CONFLICT = 'PRODUCT_SKU_CONFLICT',

  // Customer
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',

  // Order
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  CASHIER_NOT_FOUND = 'CASHIER_NOT_FOUND',

  // Project (base-template legacy)
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_NAME_CONFLICT = 'PROJECT_NAME_CONFLICT',
  PROJECT_UPDATE_FAILED = 'PROJECT_UPDATE_FAILED',
  PROJECT_DELETE_FAILED = 'PROJECT_DELETE_FAILED',

  // Generic
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
